import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Ruler, Layers, Sparkles } from 'lucide-react';
import { SiteHeader, SiteFooter } from '@/components/site-shell';
import { PackagingPreview } from '@/components/packaging-preview';

export default function Home() {
  return <><SiteHeader /><main id="main">
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" /> A NEW DIMENSION FOR YOUR IDEAS</div><h1>Big ideas.<br />Beautiful boxes.<br /><em>Brought to life.</em></h1><p>From flat artwork to something you can almost hold. Meet the next chapter of 3D Box Studio.</p><div className="hero-actions"><Link href="/studio" className="button">Explore the V2 preview <ArrowUpRight size={18} /></Link><Link href="#workflow" className="text-link">See the workflow <ArrowRight size={16} /></Link></div><span className="quiet-note">A new experience in the making. Try the concept below.</span></div><PackagingPreview /></section>
    <div className="audience-strip"><span>FOR THE PEOPLE BEHIND THE PACKAGING</span><p>Independent designers<span>·</span> Growing brands<span>·</span> Creative studios</p></div>
    <section className="workflow section" id="workflow"><div className="section-heading"><div><span className="eyebrow">LESS FRICTION. MORE CREATION.</span><h2>Your packaging.<br />A whole new perspective.</h2></div><p>We’re building around a simple idea: seeing your design should be as natural as imagining it.</p></div><div className="steps">{[{ icon: Ruler, number: '01', title: 'Start with your box', body: 'A canvas built around the dimensions and shape of your packaging.' }, { icon: Layers, number: '02', title: 'Bring your artwork', body: 'A visual workflow for placing your design on every side.' }, { icon: Sparkles, number: '03', title: 'Find its best angle', body: 'Materials, light, and perspective that help your ideas take shape.' }].map(s => <article className="step" key={s.number}><div className="step-top"><s.icon size={25} strokeWidth={1.4} /><span>{s.number}</span></div><h3>{s.title}</h3><p>{s.body}</p></article>)}</div><p className="quiet-note">The full editor is under development. This preview explores the visual direction.</p></section>
    <section className="manifesto section"><span className="eyebrow">ROOM FOR YOUR IMAGINATION</span><h2>Less wrestling with tools.<br /><em>More “that’s the one.”</em></h2><p>A focused space for packaging ideas, with the box at the center and the controls right where you need them.</p><Link className="button" href="/studio">Take a closer look <ArrowUpRight size={18} /></Link><div className="manifesto-orbit" aria-hidden="true"><span /><span /><span /></div></section>
    <section className="journal-teaser section"><div><span className="eyebrow">THE JOURNAL</span><h2>Good packaging<br />starts with good ideas.</h2><p>Our future home for practical guides, design notes, and a closer look at how packaging comes together.</p></div><Link className="text-link" href="/blog">Visit the journal <ArrowRight size={18} /></Link></section>
  </main><SiteFooter /></>;
}
