'use client';

import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Box, Check, Rotate3d, Scan, Layers, RotateCcw, MoveUpRight, ChevronDown } from 'lucide-react';
import { BoxStudy, StudyArtwork, studies, type Finish, type BoxView } from './box-study';
import styles from './home-experience.module.css';

export function HomeExperience() {
  const [studyIndex, setStudyIndex] = useState(0);
  const [finish, setFinish] = useState<Finish>('matte');
  const [view, setView] = useState<BoxView>('angle');
  const [rotation, setRotation] = useState(-26);
  const [tint, setTint] = useState(0);
  const study = studies[studyIndex];
  const colors = [study.color, '#c7d5eb', '#b8c9b6', '#d6c5df'];
  const chooseStudy = (index: number) => { setStudyIndex(index); setTint(0); };
  const reset = () => { chooseStudy(0); setFinish('matte'); setView('angle'); setRotation(-26); };
  const explore = (index: number) => { chooseStudy(index); document.getElementById('studio-demo')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); };
  return <div className={styles.home}>
    <section className={styles.hero}>
      <div className={styles.heroCopy}><div className={styles.release}><span /> 3D BOX STUDIO / THE NEXT CHAPTER</div><h1>Your packaging.<br /><span>In a new dimension.</span></h1><p>Give your artwork shape. Explore every angle. A focused workspace for the box you have in mind.</p><div className={styles.heroActions}><a className="button" href="#studio-demo">Try the interactive demo <ArrowRight size={17} /></a><a className={styles.secondaryAction} href="#examples">Explore examples <ArrowUpRight size={17} /></a></div><span className={styles.heroNote}>V2 design preview · No account needed to explore</span></div>
      <div className={styles.heroStage}><div className={styles.heroWindow}><div className={styles.heroWindowBar}><span className={styles.projectIcon}><Box size={16}/></span><strong>{study.name}</strong><span>Sample preview</span></div><div className={styles.heroCanvas}><BoxStudy study={study} color={colors[tint]} finish={finish} view={view} rotation={rotation}/><span className={styles.heroCanvasLabel}>Original artwork · {study.kind}</span></div><div className={styles.heroSamples} role="group" aria-label="Hero packaging studies">{studies.map((item,index)=><button key={item.id} onClick={()=>chooseStudy(index)} aria-label={`Preview ${item.name}`} aria-pressed={index===studyIndex}><span style={{backgroundColor:item.color}}/><span>{item.name}</span></button>)}</div></div><div className={styles.heroStageNote}><Layers size={15}/><span>Artwork. Material. Perspective.</span></div></div>
    </section>
    <section id="studio-demo" className={styles.editor} aria-label="Interactive sample packaging workspace">
      <div className={styles.editorHeader}><div className={styles.projectTitle}><span className={styles.projectIcon}><Box size={16} /></span><strong>{study.name}</strong><span className={styles.projectDivider} /><small>Sample workspace</small></div><button className={styles.reset} onClick={reset} aria-label="Reset sample workspace"><RotateCcw size={14} /><span>Reset</span></button></div>
      <div className={styles.workspace}>
        <aside className={styles.artPanel} aria-label="Sample artwork controls"><div className={styles.panelTitle}><Layers size={15} /><h2>Artwork</h2></div><p className={styles.panelHint}>Choose a packaging study</p><div className={styles.artChoices} role="group" aria-label="Choose sample artwork">{studies.map((item,index)=><button key={item.id} className={`${styles.artChoice} ${index===studyIndex?styles.selected:''}`} aria-label={`Select ${item.name}`} aria-pressed={index===studyIndex} onClick={()=>chooseStudy(index)}><div className={styles.artThumb} aria-hidden="true" style={{backgroundColor:item.color,color:item.ink}}><StudyArtwork study={item} compact /></div><span><strong>{item.name}</strong><small>{item.kind}</small></span>{index===studyIndex&&<Check size={14} />}</button>)}</div><div className={styles.flatPreview} style={{backgroundColor:colors[tint],color:study.ink}}><StudyArtwork study={study} /></div><div className={styles.panelCaption}><span>Front artwork</span><span>Sample</span></div></aside>
        <div className={styles.canvas}><div className={styles.canvasTop}><span><i /> Live sample preview</span><span>{study.kind}</span></div><BoxStudy study={study} color={colors[tint]} finish={finish} view={view} rotation={rotation} /><div className={styles.viewControls} role="group" aria-label="Camera view">{([{id:'angle',label:'Perspective',icon:Rotate3d},{id:'front',label:'Front',icon:Scan},{id:'top',label:'Top',icon:MoveUpRight}] as const).map(item=><button key={item.id} onClick={()=>setView(item.id)} aria-pressed={view===item.id} className={view===item.id?styles.activeView:''}><item.icon size={14} /><span>{item.label}</span></button>)}</div><div className={styles.canvasFoot}><span>Concept artwork · Interactive preview</span><span>W × H × D</span></div></div>
        <aside className={styles.appearance} aria-label="Packaging appearance controls"><div className={styles.panelTitle}><Box size={15} /><h2>Appearance</h2></div><fieldset><legend>Color</legend><div className={styles.palette}>{colors.map((color,index)=><button key={index} style={{backgroundColor:color}} aria-label={['Original artwork color','Mist blue','Sage','Lilac'][index]} aria-pressed={tint===index} onClick={()=>setTint(index)}>{tint===index&&<Check size={14} />}</button>)}</div></fieldset><fieldset><legend>Surface finish</legend><div className={styles.finishes}>{(['matte','paper','gloss'] as const).map(item=><button key={item} aria-pressed={finish===item} onClick={()=>setFinish(item)} className={finish===item?styles.selectedFinish:''}><span className={`${styles.finishSample} ${styles[`${item}Sample`]}`} /><span>{item==='paper'?'Textured paper':item==='gloss'?'Gloss finish':'Soft matte'}</span>{finish===item&&<Check size={13} />}</button>)}</div></fieldset><fieldset className={styles.rotation}><legend>Rotation <output>{rotation}°</output></legend><input aria-label="Rotate sample box" type="range" min="-65" max="65" value={rotation} onChange={e=>{setRotation(Number(e.target.value));setView('angle');}} /></fieldset><div className={styles.specs}><span className={styles.controlLabel}>Sample proportions</span><dl><div><dt>Width</dt><dd>{study.width}</dd></div><div><dt>Height</dt><dd>{study.height}</dd></div><div><dt>Depth</dt><dd>{study.depth}</dd></div></dl><p>Illustrative units. The full editor will use your dimensions.</p></div></aside>
      </div><div className={styles.editorFoot}><span>Explore the colors, finishes, and viewpoints above.</span><Link href="/studio">About the V2 preview <ArrowUpRight size={13}/></Link></div>
    </section>
    <section id="examples" className={styles.studiesSection}><div className={styles.sectionHeading}><div><span className={styles.kicker}>THE POSSIBILITIES</span><h2>A box is just the beginning.</h2></div><p>Different proportions. Different personalities.<br />Find a direction, then make it your own.</p></div><div className={styles.studiesGrid}>{studies.map((item,index)=><button className={styles.studyCard} key={item.id} onClick={()=>explore(index)} aria-label={`Explore ${item.name} in the demo`}><div className={`${styles.studyVisual} ${styles[`study${index}`]}`}><BoxStudy study={item} finish={index===1?'gloss':'paper'} small /></div><div className={styles.studyMeta}><span><small>{item.kind}</small><strong>{item.name}</strong></span><span className={styles.studyArrow}><ArrowUpRight size={18}/></span></div></button>)}</div><p className={styles.conceptNote}>Original concept studies. Select one to explore it in the demo.</p></section>
    <section id="workflow" className={styles.workflow}><div className={styles.workflowCopy}><span className={styles.kicker}>A CLEARER WORKFLOW</span><h2>See what flat<br />artwork can’t show.</h2><p>How the front meets the side. How the design wraps around an edge. How a finish changes the feel.</p><ol><li><span>01</span><div><h3>Find the right proportions</h3><p>Start with the shape of your product.</p></div></li><li><span>02</span><div><h3>Give every face a purpose</h3><p>See your artwork as part of a complete box.</p></div></li><li><span>03</span><div><h3>Look at the whole picture</h3><p>Explore the finish, color, and camera angle.</p></div></li></ol></div><div className={styles.workflowVisual}><div className={styles.flatArtwork} style={{color:studies[0].ink,backgroundColor:studies[0].color}}><StudyArtwork study={studies[0]} /></div><div className={styles.comparisonArrow}><ArrowRight size={24}/></div><div className={styles.workflowBox}><BoxStudy study={studies[0]} finish="paper" small /></div><div className={styles.visualLabels}><span>Flat artwork</span><span>Dimensional preview</span></div></div></section>
    <section className={styles.portfolio}><div className={styles.sectionHeading}><div><span className={styles.kicker}>BUILT AROUND YOUR IDEAS</span><h2>Small details.<br />A different shelf presence.</h2></div><p>From a first concept to a considered presentation.<br />A space to explore the possibilities of packaging.</p></div><div className={styles.portfolioImage}><Image src="/images/packaging-studies.webp" width={1344} height={752} alt="Original concept packaging: blue Ode carton, cream Field coffee box, orange Mora skincare carton, green Linden gift box, and lavender Vela box" sizes="(max-width: 700px) 100vw, 1200px" /></div><div className={styles.portfolioCaption}><span>Concept packaging collection</span><span>Design target · Not a studio export</span></div></section>
    <section className={styles.faqSection}><div><span className={styles.kicker}>BEFORE YOU START</span><h2>A few things to know.</h2><p>A fresh foundation for 3D Box Studio.</p></div><div className={styles.faqs}>{[{q:'Is this the full studio?',a:'This is an interactive design preview for V2. The sample artwork, colors, finishes, and camera controls work locally. Artwork uploads, real dimensions, saving, sharing, and exports are planned for the full editor.'},{q:'Can I use the existing 3D Box Studio?',a:'Yes. The current studio remains available at 3dboxstudio.com while we build V2 separately. Your existing account and projects are not changed by this preview.'},{q:'Will the studio support more packaging types?',a:'The studio roadmap includes bottles, jars, pouches, and different box structures with opening and folding controls. These are planned capabilities; this preview currently demonstrates closed sample cartons.'},{q:'Can I upload my own artwork here?',a:'Not yet. Choose one of the sample packaging studies to explore the new visual workflow. Your own artwork uploads will come with the full editor.'}].map(item=><details key={item.q}><summary>{item.q}<ChevronDown size={16}/></summary><p>{item.a}</p></details>)}</div></section>
    <section className={styles.closing}><div><span className={styles.kicker}>YOUR NEXT IDEA, IN 3D</span><h2>Give it a little dimension.</h2></div><a className="button" href="#studio-demo">Explore the demo <ArrowRight size={18}/></a></section>
  </div>;
}
