'use client';
import { useState,type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { UserRound,ShieldCheck,LogOut,PackageOpen,BadgeCheck,Mail } from 'lucide-react';
import { Brand } from '@/components/site-shell';
import { useAuth,type AuthUser } from './auth-provider';
import { AuthNotice } from './auth-shell';
import { PasswordField } from './auth-form';
import { formatDate } from '@/lib/i18n';
import './account-page.css';
export function AccountPage({initialUser}:{initialUser:AuthUser}){
 const auth=useAuth(),router=useRouter(),user=auth.user??initialUser;
 const [section,setSection]=useState('profile'),[name,setName]=useState(user.name??''),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function action(endpoint:string,body:unknown,method='POST'){setBusy(true);setError('');setMessage('');try{const response=await fetch(endpoint,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');setMessage(data.message);if(data.user)auth.setUser(data.user);return data;}catch(error){setError(error instanceof Error?error.message:'Could not connect.');return null;}finally{setBusy(false);}}
 async function save(event:FormEvent){event.preventDefault();await action('/api/account/profile',{name},'PATCH');}
 async function changePassword(event:FormEvent){event.preventDefault();if(password!==confirm){setError('New passwords do not match.');return;}if(await action('/api/account/password',{currentPassword:current,password})){auth.setUser(null);router.replace('/login');router.refresh();}}
 return <main className="account-page"><header className="account-header"><Brand/><div><Link className="button button-secondary button-small" href="/studio"><PackageOpen size={16}/> Studio</Link><button className="button button-secondary button-small" onClick={()=>auth.signOut()}><LogOut size={16}/> Sign out</button></div></header><div className="account-layout"><aside className="account-nav"><div className="account-person"><span>{(user.name||user.email).slice(0,2).toUpperCase()}</span><div><b>{user.name||'Your account'}</b><small>{user.email}</small></div></div><nav aria-label="Account settings"><button className={section==='profile'?'is-active':''} onClick={()=>{setSection('profile');setError('');setMessage('');}}><UserRound/> Profile</button><button className={section==='security'?'is-active':''} onClick={()=>{setSection('security');setError('');setMessage('');}}><ShieldCheck/> Password & security</button></nav></aside><section className="account-main"><header className="account-title"><p>Account</p><h1>{section==='profile'?'Profile':'Password & security'}</h1><span>Manage your workspace account.</span></header>{error&&<AuthNotice kind="error">{error}</AuthNotice>}{message&&<AuthNotice>{message}</AuthNotice>}
 {section==='profile'?<><form className="account-section" onSubmit={save}><div className="account-section-head"><h2>Personal details</h2></div><div className="account-fields"><div><label htmlFor="account-name">Display name</label><input id="account-name" autoComplete="name" value={name} maxLength={120} onChange={event=>setName(event.target.value)}/></div><div><label htmlFor="account-email">Email</label><input id="account-email" type="email" value={user.email} readOnly/></div></div><div className="account-section-actions"><button className="button button-primary" disabled={busy}>Save changes</button></div></form><section className="account-section"><div className="account-section-head"><h2>Email verification</h2><span className={`account-status ${user.emailVerified?'is-verified':''}`}>{user.emailVerified?<BadgeCheck/>:<Mail/>}{user.emailVerified?'Verified':'Pending'}</span></div>{!user.emailVerified&&<button className="button button-secondary" disabled={busy} onClick={()=>action('/api/auth/resend-verification',{})}>Resend verification email</button>}</section><section className="account-section account-facts"><h2>Account details</h2><div><span>Sign-up method</span><b>{user.signupMethod==='google'?'Google':'Email and password'}</b></div><div><span>Created</span><b>{formatDate(user.createdAt)}</b></div></section></>:<section className="account-section"><h2>Change password</h2>{user.hasPassword?<form className="auth-form" onSubmit={changePassword}><PasswordField id="current-password" label="Current password" value={current} onChange={setCurrent} autoComplete="current-password" minLength={1}/><PasswordField id="new-password" label="New password" value={password} onChange={setPassword}/><PasswordField id="confirm-password" label="Confirm new password" value={confirm} onChange={setConfirm}/><p>Changing your password signs you out on all devices.</p><button className="button button-primary" disabled={busy}>Change password</button><Link className="auth-inline-link" href="/forgot-password">Forgot current password?</Link></form>:<AuthNotice kind="info">Your account uses Google sign-in. Manage your password with Google.</AuthNotice>}</section>}
 </section></div></main>;
}
